/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const TicketsLazyRouteImport = createFileRoute('/tickets')()
const TicketsIndexLazyRouteImport = createFileRoute('/tickets/')()
const TicketsTicketIdLazyRouteImport = createFileRoute('/tickets/$ticketId')()

const TicketsLazyRoute = TicketsLazyRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/tickets.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexLazyRoute = TicketsIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TicketsLazyRoute,
} as any).lazy(() => import('./routes/tickets.index.lazy').then((d) => d.Route))
const TicketsTicketIdLazyRoute = TicketsTicketIdLazyRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => TicketsLazyRoute,
} as any).lazy(() =>
  import('./routes/tickets.$ticketId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tickets': typeof TicketsLazyRouteWithChildren
  '/tickets/$ticketId': typeof TicketsTicketIdLazyRoute
  '/tickets/': typeof TicketsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tickets/$ticketId': typeof TicketsTicketIdLazyRoute
  '/tickets': typeof TicketsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tickets': typeof TicketsLazyRouteWithChildren
  '/tickets/$ticketId': typeof TicketsTicketIdLazyRoute
  '/tickets/': typeof TicketsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tickets' | '/tickets/$ticketId' | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tickets/$ticketId' | '/tickets'
  id: '__root__' | '/' | '/tickets' | '/tickets/$ticketId' | '/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TicketsLazyRoute: typeof TicketsLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexLazyRouteImport
      parentRoute: typeof TicketsLazyRoute
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdLazyRouteImport
      parentRoute: typeof TicketsLazyRoute
    }
  }
}

interface TicketsLazyRouteChildren {
  TicketsTicketIdLazyRoute: typeof TicketsTicketIdLazyRoute
  TicketsIndexLazyRoute: typeof TicketsIndexLazyRoute
}

const TicketsLazyRouteChildren: TicketsLazyRouteChildren = {
  TicketsTicketIdLazyRoute: TicketsTicketIdLazyRoute,
  TicketsIndexLazyRoute: TicketsIndexLazyRoute,
}

const TicketsLazyRouteWithChildren = TicketsLazyRoute._addFileChildren(
  TicketsLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TicketsLazyRoute: TicketsLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
